### ISSUE TITLE
I want to add problems asked in FAANG interviews and are otherwise most popular

### ISSUE THREAD

**Issue by PayelChaudhuri** [GDSC-TMSL/ProjectAlgorithms#22]
# I want to add problems asked in FAANG interviews and are otherwise most popular. Mainly they are algorithms and all. 
### Please allow me to contribute.

Thank you.

**Comment by PayelChaudhuri** [comment]
@Sabyasachi-Seal Dada, do allow me since I have to complete this before 24th for the acceptance period of 7 days to start.

**Comment by Sabyasachi-Seal** [comment]
@PayelChaudhuri go for it

**Comment by PayelChaudhuri** [comment]
@Sabyasachi-Seal Done :)
Do check it if you will :))
